export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER_UPDATED_SUCCESS';
export const REGISTER_CREATED_SUCCESS = 'REGISTER_CREATED_SUCCESS';

export const COURSE_REQUEST = 'COURSE_REQUEST';
export const COURSE_FAILURE = 'COURSE_FAILURE';
export const COURSE_UPDATED_SUCCESS = 'COURSE_UPDATED_SUCCESS';
export const COURSE_CREATED_SUCCESS = 'COURSE_CREATED_SUCCESS';

export const LESSON_REQUEST = 'LESSON_REQUEST';
export const LESSON_FAILURE = 'LESSON_FAILURE';
export const LESSON_UPDATED_SUCCESS = 'LESSON_UPDATED_SUCCESS';
export const LESSON_CREATED_SUCCESS = 'LESSON_CREATED_SUCCESS';

export const SUPPORTMAT_REQUEST = 'SUPPORTMAT_REQUEST';
export const SUPPORTMAT_FAILURE = 'SUPPORTMAT_FAILURE';
export const SUPPORTMAT_UPDATED_SUCCESS = 'SUPPORTMAT_UPDATED_SUCCESS';
export const SUPPORTMAT_CREATED_SUCCESS = 'SUPPORTMAT_CREATED_SUCCESS';

export const SUBSCRIPTION_REQUEST = 'SUBSCRIPTION_REQUEST';
export const SUBSCRIPTION_FAILURE = 'SUBSCRIPTION_FAILURE';
export const SUBSCRIPTION_UPDATED_SUCCESS = 'SUBSCRIPTION_UPDATED_SUCCESS';
export const SUBSCRIPTION_CREATED_SUCCESS = 'SUBSCRIPTION_CREATED_SUCCESS';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
